apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbnb-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbnb-app
  template:
    metadata:
      labels:
        app: airbnb-app
    spec:
      containers:
      - name: frontend
        image: sholly333/airbnb-app-frontend:latest  # Replace with your image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      - name: backend
        image: sholly333/airbnb-app-backend:latest  # Replace with your image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: BCRYPT_SALT   # ✅ Corrected this line
          value: "$2b$10$HeeRPL7YACkhv4dpmck5AO"
---
apiVersion: v1
kind: Service
metadata:
  name: airbnb-app-service
spec:
  selector:
    app: airbnb-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
