apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbnb-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbnb-app
  template:
    metadata:
      labels:
        app: airbnb-app
    spec:
      containers:
      - name: frontend
        image: ${FRONTEND_IMAGE}  # Using the image variable here
        ports:
        - containerPort: 3000
      - name: backend
        image: ${BACKEND_IMAGE}  # Using the image variable here
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: airbnb-app-service
spec:
  selector:
    app: airbnb-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer